//
// Generated by JTB 1.3.2
//

package visitor;
import java.util.*;
import syntaxtree.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   public StringBuilder code = new StringBuilder();
   public int temp_cnt = 1000;
   public String newtemp(){
      temp_cnt++;
      return ("TEMP " + Integer.toString(temp_cnt));
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      code.append("MAIN\n");
      n.f1.accept(this, argu);
      code.append("END\n");
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null; 
      _ret = n.f0.accept(this, argu); 
      return _ret;
   }


   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null; 
      String label = (String)n.f0.accept(this, argu); 
      n.f1.accept(this, argu); 
      String integer = (String)n.f2.accept(this, argu); 
      n.f3.accept(this, argu); 
      code.append(" [" + integer + "] \n"); 
      code.append("BEGIN\n"); 
      String exp = (String)n.f4.accept(this, argu); 
      code.append("RETURN\n" + exp + "\n"); 
      code.append("END\n"); 
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      code.append("NOOP\n");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      code.append("ERROR\n");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      String cond = (String)n.f1.accept(this, argu);
      String tmp = newtemp();
      code.append("MOVE " + tmp + " " + cond + "\n");
      code.append("    CJUMP " + tmp + " ");
      String label = (String)n.f2.accept(this, argu);
      code.append("\n");
      return null;
   }


   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      code.append("JUMP ");
      String label = (String)n.f1.accept(this, argu);
      code.append("\n");
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String temp = newtemp();
      String exp1 = (String)n.f1.accept(this, argu);
      String number = (String)n.f2.accept(this, argu);
      String exp2 = (String)n.f3.accept(this, argu);
      if (exp2.startsWith("TEMP"))
         code.append("HSTORE " + exp1 + " " + number + " " + exp2 + "\n");
      else {
         String tmp = newtemp();
         code.append("MOVE " + tmp + " " + exp2 + "\n");
         code.append("HSTORE " + exp1 + " " + number + " " + tmp + "\n");
      }
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String tempexp = (String)n.f1.accept(this, argu);
      String exp = (String)n.f2.accept(this, argu);
      String number = (String)n.f3.accept(this, argu);
      code.append("HLOAD " + tempexp + " " + exp + " " + number + "\n");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      String temp = (String)n.f1.accept(this, argu);
      String exp = (String)n.f2.accept(this, argu);

      if(exp.startsWith("CALL") || exp.startsWith("HALLOCATE") || exp.startsWith("MINUS") || exp.startsWith("PLUS") || exp.startsWith("TIMES")){
         String tmp = newtemp();
         code.append("MOVE " + tmp + " " + exp + "\n");
         code.append("MOVE " + temp + " " + tmp + "\n");
      }else{
         code.append("MOVE " + temp + " " + exp + "\n");
      }
      return null;
   }


   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      String exp = (String)n.f1.accept(this, argu);
      String tmp = newtemp();
      code.append("MOVE " + tmp + " " + exp + "\n");
      code.append("PRINT " + tmp + "\n");
      return null;
   }


   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      String t = newtemp();
      n.f1.accept(this, argu); 
      String exp = (String)n.f3.accept(this, argu);
      code.append("MOVE " + t + " " + exp + "\n");
      return (R)t;
   }


   /**
 * f0 -> "CALL"
 * f1 -> Exp()
 * f2 -> "("
 * f3 -> ( Exp() )*
 * f4 -> ")"
 */
public R visit(Call n, A argu) {
    String t1 = newtemp();
    String exp = (String)n.f1.accept(this, argu);
    if (!exp.startsWith("TEMP") && 
        !exp.matches("\\d+") && 
        !exp.matches("[a-zA-Z][a-zA-Z0-9_]*")) {
        String tFunc = newtemp();
        code.append("MOVE " + tFunc + " " + exp + "\n");
        exp = tFunc;
    }
    
    StringBuilder args = new StringBuilder();
    if(n.f3.present()) {
        for(Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            String arg = (String) e.nextElement().accept(this, argu);
            if(!arg.startsWith("TEMP")) {
                String tArg = newtemp();
                code.append("MOVE " + tArg + " " + arg + "\n");
                arg = tArg;
            }
            if(args.length() > 0) args.append(" ");
            args.append(arg);
        }
    }
    
    code.append("MOVE " + t1 + " CALL " + exp + " (" + args.toString() + ")\n");
    return (R)t1;
}

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String exp = (String)n.f1.accept(this, argu);
      return (R)("HALLOCATE " + exp);
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      String op = (String)n.f0.accept(this, argu);
      String left = (String)n.f1.accept(this, argu);
      String right = (String)n.f2.accept(this, argu);
      String res = newtemp();

      if (!left.startsWith("TEMP")) {
         String t1 = newtemp();
         code.append("MOVE " + t1 + " " + left + "\n");
         left = t1;
      }
      if (!right.startsWith("TEMP")) {
         String t2 = newtemp();
         code.append("MOVE " + t2 + " " + right + "\n");
         right = t2;
      }

      code.append("MOVE " + res + " " + op + " " + left + " " + right + "\n");
      return (R) res;
   }


   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      return (R) n.f0.choice.toString();
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      return (R)("TEMP " + n.f1.f0.toString());
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      return (R) n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      String label = n.f0.toString();
      // Labels should be on their own line without indentation
      code.append(label + " ");
      return (R) label;
   }

}
